"use client";

import { CheckSquare, Wand2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { FileUpload } from "@/components/ui/file-upload";
import { PageHeader } from "@/components/ui/page-header";
import { ProgressRing } from "@/components/ui/progress-ring";
import { useResumeUpload } from "@/components/dashboard/resume-upload-context";

export default function AtsCheckerPage() {
  const upload = useResumeUpload();

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="ATS Checker"
        title="Keyword alignment"
        description="Dedicated ATS workspace prepared for future job-description comparison endpoints."
      />

      <div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
        <Card>
          <h2 className="text-lg font-semibold text-white">Resume Upload</h2>
          <div className="mt-5">
            <FileUpload
              selectedFile={upload.selectedFile}
              error={upload.uploadError}
              success={upload.uploadSuccess}
              isUploading={upload.isUploading}
              onClear={upload.clearFile}
              onSelect={upload.selectFile}
              onUpload={() => void upload.uploadResume()}
            />
          </div>
        </Card>
        <Card>
          <h2 className="text-lg font-semibold text-white">Job Description Input</h2>
          <textarea className="form-input mt-4 min-h-64 resize-none" placeholder="Paste the target job description" />
          <button className="button-primary mt-4" type="button">
            <Wand2 size={16} />
            Check ATS Match
          </button>
        </Card>
      </div>

      <div className="grid gap-5 lg:grid-cols-[18rem_1fr_1fr]">
        <Card>
          <ProgressRing label="Keyword Match %" size="lg" />
        </Card>
        <EmptyState icon={CheckSquare} title="Missing Keywords" description="Keyword gaps will appear here after the ATS matching endpoint is connected." />
        <EmptyState icon={Wand2} title="Suggestions" description="Suggestions will be generated by future backend responses." />
      </div>
    </div>
  );
}
